#!/usr/bin/python3
import sys
import os


def func(file):
    with open(file, 'r') as f:
        for number in f:
            num = int(number)
            result = factor(num)
            print("{}={}*{}" .format(num, num // result, result))


def factor(i):
    for j in range(2, i + 1):
        if i % j == 0:
            return j


if __name__ == "__main__":
    func(sys.argv[1])
